/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef , useState, useEffect} from 'react'
import * as THREE from "three";
import { useGLTF } from '@react-three/drei'
import useImageStore from "../hooks/useImageStore"; // Importer votre hook Zustand

export function CoqueIP12(props) {
  const { nodes, materials } = useGLTF('/models/coqueIP12.glb')

  const imageUrl = useImageStore((state) => state.imageUrl); // Récupérer l'URL de l'image depuis le store

  const [texture, setTexture] = useState(null);

  useEffect(() => {
    if (imageUrl) {
      const loader = new THREE.TextureLoader();
      loader.load(imageUrl, (loadedTexture) => {
        setTexture(loadedTexture);
        materials.Default.map = loadedTexture;
        materials.Default.needsUpdate = true;
      });
    }
  }, [imageUrl, materials.Default]);

  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh.geometry}
          material={materials.Default}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_1.geometry}
          material={materials['Material.001']}
        />
      </group>
    </group>
  )
}

export default CoqueIP12;

useGLTF.preload('/models/coqueIP12.glb')